from codrone_edu.drone import *
drone = Drone()
drone.pair()
drone.takeoff()
drone.hover(3)

print("giro 1")
drone.turn_degree(90, 3)
drone.hover(1)
print("giro 2")
drone.turn_degree(180, 3)
drone.hover(1)
print("giro 3")
drone.turn_degree(270, 3)
drone.hover(1)
print("Giro 4")
drone.turn_degree(0, 3)
drone.hover(1)
drone.land()